CREATE TABLE users (
   id SERIAL PRIMARY KEY,
   username VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL UNIQUE,
   document_number VARCHAR(80) NOT NULL UNIQUE,
   address VARCHAR(255) NOT NULL,
   role VARCHAR(50)
);
